### ISSUE TITLE
Failed to lookup view "error" in views directory

### ISSUE THREAD

**Issue by jw0903** [wenzi0github/node_express_forum#1]
想请问一下按照您给的步骤下载安装了，出现这样的错误怎么解决？

**Comment by jw0903** [comment]
在views目录下添加了一个空的error.ejs文件之后，运行产生500错误？

**Comment by wenzi0github** [comment]
每次修改代码后，都要`ctrl+C`停止一下，然后再重新启动的，我没弄热加载

**Comment by jw0903** [comment]
每次修改之后都有重新运行，但就是跑不起来

**Comment by wenzi0github** [comment]
你那边的node版本是多少呢，不太清楚会不会跟node版本有关系，我这里node版本是6.9.4，npm版本是3.10.10

**Comment by jw0903** [comment]
node版本是6.10.0，npm是3.10.10，你是重新下载你的项目运行了吗？

**Comment by jw0903** [comment]
Error: Failed to lookup view "error" in views directory "F:\node_express_forum\views"
   at EventEmitter.render (F:\node_express_forum\node_modules\express\lib\application.js:579:17)
   at ServerResponse.render (F:\node_express_forum\node_modules\express\lib\response.js:960:7)
   at F:\node_express_forum\app.js:65:7
   at Layer.handle_error (F:\node_express_forum\node_modules\express\lib\router\layer.js:71:5)
   at trim_prefix (F:\node_express_forum\node_modules\express\lib\router\index.js:310:13)
   at F:\node_express_forum\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (F:\node_express_forum\node_modules\express\lib\router\index.js:330:12)
   at next (F:\node_express_forum\node_modules\express\lib\router\index.js:271:10)
   at Layer.handle_error (F:\node_express_forum\node_modules\express\lib\router\layer.js:67:12)
   at trim_prefix (F:\node_express_forum\node_modules\express\lib\router\index.js:310:13)

出现这样的错误，你的views文件夹中有没有error文件

**Comment by wenzi0github** [comment]
找到原因了，是因为加载时没有`favicon.ico`，导致404，触发了根目录下app.js中最后的2个中间件，这个中间件触发后，要调用error模板，但是views中没有error模板，导致控制台报错了：

```javascript
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};
  // render the error page
  res.status(err.status || 500);
  res.render('error');
});
```

可是你那边添加error.ejs后会导致500的错误，我这里没有复现

**Comment by jw0903** [comment]
哦哦，原来是我之前只是单单创建了一个error.ejs文件，里面是空的，所有才出现那样的错误。那你的这个项目里面就是缺少了error模版咯

**Comment by wenzi0github** [comment]
是的，多谢指正，我已经把error模板添加上了！

**Comment by jw0903** [comment]
额， 我新手一个，还是不太懂，你的error模版添加了只是输出了错误信息，但是并不能跳转到正常界面，那原先的favicon.ico不能加载的问题怎么解决？

**Comment by wenzi0github** [comment]
你需要手动在根目录放一个favicon.ico
